services:
  - type: web
    name: telegram-qr-image-bot
    runtime: python
    plan: free
    buildCommand: pip install --default-timeout=120 -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: TARGET_GROUP_ID
        sync: false
